# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wangGiftType', models.CharField(choices=[('food', '食物'), ('clothing', '服装配饰'), ('jewelry', '钟表首饰'), ('cosmetic', '化妆品'), ('sport_equipment', '运动户外'), ('digital', '电器数码'), ('gadgets', '小玩意'), ('handmade', '手工物件'), ('nijigen', '二次元'), ('book', '图书音像'), ('study_source', '学习资源'), ('others', '其它')], max_length=15, verbose_name='回礼类型')),
                ('getGiftId', models.CharField(max_length=10, verbose_name='回礼ID')),
            ],
            options={
                'permissions': (('manager', '礼物系统管理员'),),
            },
        ),
        migrations.CreateModel(
            name='ExchangeGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aimGroup', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('both', '男女不限')], max_length=6, null=True, verbose_name='希望送给')),
            ],
            options={
                'permissions': (('manager', '礼物系统管理员'),),
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftId', models.CharField(max_length=10, unique=True, verbose_name='礼物ID')),
                ('name', models.CharField(max_length=100, verbose_name='礼物名')),
                ('type', models.CharField(choices=[('food', '食物'), ('clothing', '服装配饰'), ('jewelry', '钟表首饰'), ('cosmetic', '化妆品'), ('sport_equipment', '运动户外'), ('digital', '电器数码'), ('gadgets', '小玩意'), ('handmade', '手工物件'), ('nijigen', '二次元'), ('book', '图书音像'), ('study_source', '学习资源'), ('others', '其它')], max_length=15, verbose_name='礼物类别')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='礼物描述')),
            ],
            options={
                'permissions': (('manager', '礼物系统管理员'),),
            },
        ),
        migrations.CreateModel(
            name='GivenGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenPerson', models.CharField(max_length=100, verbose_name='收礼者')),
                ('givenPhone', models.CharField(max_length=11, verbose_name='收礼者手机号')),
                ('givenAdress', models.CharField(max_length=1000, verbose_name='收礼者具体地址')),
                ('isAnonymous', models.BooleanField(default=False, verbose_name='匿名')),
                ('gift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='giftchange.Gift')),
            ],
            options={
                'permissions': (('manager', '礼物系统管理员'),),
            },
        ),
        migrations.CreateModel(
            name='Wechat_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, verbose_name='openId')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机')),
                ('area', models.CharField(default='南区', max_length=1, null=True, verbose_name='居住区域')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftchange.Gift')),
            ],
            options={
                'permissions': (('manager', '礼物系统管理员'),),
            },
        ),
        migrations.AddField(
            model_name='exchangegift',
            name='gift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='giftchange.Gift'),
        ),
        migrations.AddField(
            model_name='changeresult',
            name='exchangegift',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='giftchange.ExchangeGift'),
        ),
    ]
