# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changeresult',
            options={'permissions': (('manager', '礼物系统管理员'),), 'verbose_name': '互换结果', 'verbose_name_plural': '互换结果'},
        ),
        migrations.AlterModelOptions(
            name='exchangegift',
            options={'permissions': (('manager', '礼物系统管理员'),), 'verbose_name': '可互换礼物', 'verbose_name_plural': '可互换礼物'},
        ),
        migrations.AlterModelOptions(
            name='gift',
            options={'permissions': (('manager', '礼物系统管理员'),), 'verbose_name': '礼物', 'verbose_name_plural': '礼物'},
        ),
        migrations.AlterModelOptions(
            name='givengift',
            options={'permissions': (('manager', '礼物系统管理员'),), 'verbose_name': '被赠予礼物', 'verbose_name_plural': '被赠予礼物'},
        ),
        migrations.AlterField(
            model_name='wechat_user',
            name='gift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='giftchange.Gift'),
        ),
    ]
