# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftchange', '0002_auto_20161121_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechat_user',
            name='area',
            field=models.CharField(choices=[('C', '南区'), ('A', '西南'), ('B', '斋区')], default='南区', max_length=1, null=True, verbose_name='居住区域'),
        ),
    ]
