# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftchange', '0003_auto_20161121_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechat_user',
            name='openid',
        ),
        migrations.AddField(
            model_name='wechat_user',
            name='stu_no',
            field=models.CharField(default=2015150006, max_length=10, verbose_name='学号'),
            preserve_default=False,
        ),
    ]
