# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftchange', '0005_auto_20161121_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givengift',
            name='isAnonymous',
        ),
        migrations.AddField(
            model_name='gift',
            name='isAnonymous',
            field=models.BooleanField(default=False, verbose_name='匿名'),
        ),
    ]
