# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftchange', '0007_auto_20161121_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='giftId',
            field=models.CharField(max_length=10, null=True, verbose_name='礼物ID'),
        ),
    ]
