# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftchange', '0009_auto_20161121_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftsystem_user',
            name='gift',
        ),
        migrations.AddField(
            model_name='gift',
            name='own',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='giftchange.GiftSystem_user'),
        ),
    ]
