# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-25 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftchange', '0011_auto_20161121_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='isUsed',
            field=models.BooleanField(default=False, verbose_name='是否已完成交换或赠与'),
        ),
    ]
