# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-26 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftchange', '0012_gift_isused'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftsystem_user',
            name='wechat',
            field=models.CharField(max_length=50, null=True, verbose_name='微信号'),
        ),
    ]
