# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-29 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftchange', '0014_auto_20161126_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeresult',
            name='wangGiftType',
            field=models.CharField(choices=[('01', '食物'), ('02', '服装配饰'), ('03', '钟表首饰'), ('04', '化妆品'), ('05', '运动户外'), ('06', '电器数码'), ('07', '小玩意'), ('08', '手工物件'), ('09', '二次元'), ('10', '图书音像'), ('11', '学习资源'), ('12', '其它')], max_length=50, verbose_name='回礼类型'),
        ),
    ]
